apiVersion: v1
data:
  {{- toYaml .Values.node | nindent 2 }}
kind: ConfigMap
metadata:
  name: node

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.json: |-
    {
      "log_config_name": "log_cfg.yml",
      "ton_global_config_name": "ton-global.config.json",
      "use_global_config": true,
      "ip_address": null,
      "adnl_node": {
        "ip_address": "0.0.0.0:30303",
        "keys": [
          {
            "tag": 1,
            "data": {
              "type_id": 1209251014,
              "pub_key": null,
              "pvt_key": "mKpRdJhiiSt9eAMjXuJm4Zj1KtFbt8xH1b//9T8wPXA="
            }
          },
          {
            "tag": 2,
            "data": {
              "type_id": 1209251014,
              "pub_key": null,
              "pvt_key": "yJAnqPehBg++VGfsGCJjRUtaC6/OVv3xZQQqMFa5A08="
            }
          }
        ]
      },
      "overlay_peers": [],
      "kafka_consumer_config": {
        "group_id": "101",
        "brokers": "kafka",
        "topic": "requests",
        "session_timeout_ms": 6000,
        "run_attempt_timeout_ms": 1000
      },
      "external_db_config": {
        "block_producer": {
          "enabled": true,
          "brokers": "kafka",
          "message_timeout_ms": 100,
          "topic": "blocks",
          "attempt_timeout_ms": 100,
          "message_max_size": 1000000,
          "big_messages_storage": "big-blocks"
        },
        "raw_block_producer": {
          "enabled": false,
          "brokers": "",
          "message_timeout_ms": 0,
          "topic": "",
          "attempt_timeout_ms": 0,
          "message_max_size": 0,
          "big_messages_storage": ""
        },
        "message_producer": {
          "enabled": true,
          "brokers": "kafka",
          "message_timeout_ms": 100,
          "topic": "messages",
          "attempt_timeout_ms": 100,
          "message_max_size": 1000000,
          "big_messages_storage": "big-messages"
        },
        "transaction_producer": {
          "enabled": true,
          "brokers": "kafka",
          "message_timeout_ms": 100,
          "topic": "transactions",
          "attempt_timeout_ms": 100,
          "message_max_size": 1000000,
          "big_messages_storage": "big-transactions"
        },
        "account_producer": {
          "enabled": true,
          "brokers": "kafka",
          "message_timeout_ms": 100,
          "topic": "accounts",
          "attempt_timeout_ms": 100,
          "message_max_size": 4000000,
          "big_messages_storage": "big-accounts"
        },
        "block_proof_producer": {
          "enabled": true,
          "brokers": "kafka",
          "message_timeout_ms": 100,
          "topic": "blocks_signatures",
          "attempt_timeout_ms": 100,
          "message_max_size": 2000000,
          "big_messages_storage": "big-block-proofs"
        },
        "bad_blocks_storage": "bad-blocks"
      }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-config
data:
  default_config.json: |-
    {
        "log_config_name": "log_cfg.yml",
        "ton_global_config_name": "ton-global.config.json",
        "use_global_config": true,
        "ip_address": "0.0.0.0:30303",
        "overlay_peers": [
        ],
        "shard_keeper": {
            "get_peer_attempt_timeout_ms": 1000,
            "download_next_block_full_timeout_ms": 1000,
            "download_block_full_timeout_ms": 1000
        },
        "kafka_consumer_config": {
            "group_id": "101",
            "brokers": "kafka",
            "topic": "requests",
            "session_timeout_ms": 6000,
            "run_attempt_timeout_ms": 1000
        },
        "external_db_config": {
            "block_producer": {
                "enabled": true,
                "brokers": "kafka",
                "message_timeout_ms": 100,
                "topic": "blocks",
                "attempt_timeout_ms": 100,
                "message_max_size": 1000000,
                "big_messages_storage": "big-blocks"
            },
            "message_producer": {
                "enabled": true,
                "brokers": "kafka",
                "message_timeout_ms": 100,
                "topic": "messages",
                "attempt_timeout_ms": 100,
                "message_max_size": 1000000,
                "big_messages_storage": "big-messages"
            },
            "transaction_producer": {
                "enabled": true,
                "brokers": "kafka",
                "message_timeout_ms": 100,
                "topic": "transactions",
                "attempt_timeout_ms": 100,
                "message_max_size": 1000000,
                "big_messages_storage": "big-transactions"
            },
            "account_producer": {
                "enabled": true,
                "brokers": "kafka",
                "message_timeout_ms": 100,
                "topic": "accounts",
                "attempt_timeout_ms": 100,
                "message_max_size": 4000000,
                "big_messages_storage": "big-accounts"
            },
            "block_proof_producer": {
                "enabled": true,
                "brokers": "kafka",
                "message_timeout_ms": 100,
                "topic": "blocks_signatures",
                "attempt_timeout_ms": 100,
                "message_max_size": 2000000,
                "big_messages_storage": "big-block-proofs"
            },
            "bad_blocks_storage": "bad-blocks"
        }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: log-cfg
data:
  log_cfg.yml: |-
    # Scan this file for changes every 30 seconds
    # https://docs.rs/log4rs/0.8.3/log4rs/encode/pattern/index.html
    refresh_rate: 30 seconds
    
    appenders:
      stdout:
        kind: console
        encoder:
          pattern: "{d(%s.%f)} {l} [{h({t})}] {I}: {m}{n}"
    
      stdout_ref:
        kind: console
        encoder:
          pattern: "{f}:{L} {l} [{h({t})}] {I}: {m}{n}"
    
      tvm_stdout:
        kind: console
        encoder:
          pattern: "{m}{n}"
    
    root:
      level: warn
      appenders:
        - stdout
    
    loggers:
      # node messages
      node:
        level: debug
        appenders:
          - stdout
    
      ton_node:
        level: trace
        additive: false
        appenders:
          - stdout
    
      # adnl messages
      adnl:
        level: debug
        appenders:
          - stdout
    
      # block messages
      ton_block:
        level: debug
        appenders:
          - stdout
    
      # block messages
      executor:
        level: debug
        appenders:
          - stdout
    
      # tvm messages
      tvm:
        level: trace
        appenders:
          - tvm_stdout
    
      librdkafka:
        level: warn
        appenders:
          - stdout
    
      validator:
        level: debug
        appenders:
          - stdout_ref  

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ton-global
data:
  ton-global.config.json: |-
    {
        "@type": "config.global",
        "dht": {
            "@type": "dht.config.global",
            "k": 6,
            "a": 3,
            "static_nodes": {
                "@type": "dht.nodes",
                "nodes": [
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"dV01rTYvL4JFtLdo2hjSimAZbVx9JpEOrzt75Kk+Dt4="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":869426039,"port":30303}],"version":1596719996,"reinit_date":1596719996,"priority":0,"expire_at":0},"version":1596800266,"signature":"W25R5vm1vRKYU5NREfbBQ9OjLHByBIMtiBambCa0gEv2iq+JkdJV4t7XfNQz6b6KwvDiHv6wuee3Mza8HENnDg=="},
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"6/Xgfb/+Awv3FzpQ2WqqtQY3QZvRKUK/CgRf+9zk7g0="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":869426050,"port":30303}],"version":1596668411,"reinit_date":1596668411,"priority":0,"expire_at":0},"version":1596800266,"signature":"rRrko6OXA/Ee84/NpHSGoH/ZeGXS7e6DM/rLv8tbubaSgf5Fg3Q0tJ+1y4fVaAbvWsfwyQpGVWCqIhE9So/WAg=="},
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"fJyZ6myaAcKgPmxdBOd8ENdz3OcrmBOS9y9GB36m5tE="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":869426052,"port":30303}],"version":1596340024,"reinit_date":1596340024,"priority":0,"expire_at":0},"version":1596800259,"signature":"jydAEIdETylOOWc5sKfXYig1L6OD7fN+K9e5CFYHnUsdyhKrKctsqSl6IDvAsR12GxydQT6pLm69UaYPEvbcCA=="},
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"rMlcP+Hc+6tpA93C1zdKdNlzCvHyFh2Wq9F8AenRwSk="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":869426054,"port":30303}],"version":1596339996,"reinit_date":1596339996,"priority":0,"expire_at":0},"version":1596800261,"signature":"V/GakdVuSXlO9HXt37f1/r2TwR805LslN7Mz3p7Ag/eboyYEH2FlUq93i3jNXhYpuXUV783jm6WCY9f5EsBoDw=="},
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"tJrjq0myhgiYSeYRU926mzuwkyMoNwyFYJwyOHMSH5k="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":861657602,"port":30303}],"version":1596190439,"reinit_date":1596190439,"priority":0,"expire_at":0},"version":1596805015,"signature":"7i+2cPN3yqzmuJgyjUtyp65huf6gwJUJq1l3TOABc0Wxt9Tg/HCbBjbnbNynioeMhFMyesX8h5zIUI1AVimOCQ=="},
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"7pxRm+NnloQKo27VWajHMDA144nxyGTCnFCFPTSlLe4="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":1608106262,"port":30310}],"version":1596237888,"reinit_date":1596237888,"priority":0,"expire_at":0},"version":1596805019,"signature":"4VWx91Ke0SVI38h2BGXgxo3AYz/n2n4ysbLk+gG80+7oNZ2pbDob3X0E2nD9eY50gm/taZyALiY+1ll2WMcNCg=="},
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"iAeYNBT0tuxUpkYJwgQ+2CaqNAEDbntpJ+BgLVSfUZg="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":869429907,"port":30303}],"version":1596754253,"reinit_date":1596754253,"priority":0,"expire_at":0},"version":1596805017,"signature":"kGDNs8iqeRx9XdjGnL+rxz0hHYG1BZ2Hurw3WaQnRrtdYto60eUrzfbxeC04v8h6U4vLuZXUT7Mm1/rj6F7tAA=="},
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"slkg+NLeOP0ozp8niP8mYZvm7kh82M4wqf67Dh6EKtc="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":869429406,"port":30303}],"version":1596600791,"reinit_date":1596600791,"priority":0,"expire_at":0},"version":1596805018,"signature":"i/FYAzWVziH/5g0+JlkxOPidzIwJhyQtuWDZuXLenrw+zyVEmhgup3voA6AVK5HEznSDduJ5mgzKu/H5A682Cw=="},
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"B8G6auRkWw9fuvUQFqWnOiOw0LMazyl8qjq7GpNV5V8="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":869429407,"port":30303}],"version":1596600757,"reinit_date":1596600757,"priority":0,"expire_at":0},"version":1596804986,"signature":"OcD+6tBbHTtbvCFHW7HOKZXbm+NjnK42D8QjNmj4hGxpa4EH2/DPRcukVLFG+Fvr5/SyG4pTHYm1HehkdXX4AQ=="},
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"gPq1MnIxk/6Fm1OKSgfKd5hO/KBOlkKRX616HamdM7g="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":-1010183191,"port":30310}],"version":1595024634,"reinit_date":1595024634,"priority":0,"expire_at":0},"version":1596805013,"signature":"CdaU19wYpfJKIDLeK8V8doKEx7OnbyxMFmSmQG9SkMluqoOkKx4/3ilYCxVOKbrQ22QAH4mrrPcnCPMxLTzzCg=="},
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"FGl09818+B5eao82Q3UR/XRL7GUS0ImtN8VguksTwkM="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":-1067244496,"port":30310}],"version":1596411492,"reinit_date":1596411492,"priority":0,"expire_at":0},"version":1596805014,"signature":"FY2COgtLeZTj2r/Yo/mYrPaVOpaLPuxXTaGRzI0kRM21Osm5VNOp7ehVYfKSzGKpi0BSLJeyKNypYTJCC8NuCw=="},
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"2OYVE4F2eGzY6zG9o/DEk5vRua+RY4waFUWsgcGDHXk="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":869429906,"port":30303}],"version":1596190346,"reinit_date":1596190346,"priority":0,"expire_at":0},"version":1596805019,"signature":"Zlj131BxtJCzFXwwCmU2+77uHbNmd7fXHf0uy3All7NM3O9mh5Jkqjp4vCi8xXpgjh/6r79Ot3o1tbwrJHsrBA=="},
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"7ipevdaPe/CFrESWW6/rwDgMicH6az2pRjK2doTJKMQ="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":-824328486,"port":30310}],"version":1595979999,"reinit_date":1595979999,"priority":0,"expire_at":0},"version":1596805014,"signature":"qpG+BW1zHUGonR+nNkb3heBOVGh44dF41EJ/YDkLHCIL4MlyTN8+o8OPT61f3itD5NZfwYSpwWWTPTYXzlFMDQ=="},
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"0OSAEbxI8SnQYFHgiqT2iw3Buc34+Vu8cub78GAOLFQ="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":-1125952410,"port":30310}],"version":1596800834,"reinit_date":1596800834,"priority":0,"expire_at":0},"version":1596805003,"signature":"A9/oJjLajnHthvgG/TKE49ts15MdVOaajFy9eXaYXSXRu/37HOd857TWduNd1L6xZDIxvqIAJ+V9vNt4YvZhDg=="},
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"BZfZCpyfr8q/HZDmr6rUkABcCn+yNrweftsgF4xIf20="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":869426065,"port":30303}],"version":1596190162,"reinit_date":1596190162,"priority":0,"expire_at":0},"version":1596805013,"signature":"9fD4+yqv7pqHaP1wnHENs7BufVUwLg/4cQm1PglN0UCYy+KkemFlrsW7bW0cPGrBpLJ5PMne7QUXzHcxBqWPCg=="},
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"gpb4+jGvtoBAe3lRDUjafsHrmirK8Q6yEMeD5jhs7Sg="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":869429611,"port":30303}],"version":1596190455,"reinit_date":1596190455,"priority":0,"expire_at":0},"version":1596805002,"signature":"hLHy84StsOPVTa98IJWVtDveeCT+mT9mkWVHzbXI/yqDOSWDyOFV7SHtFVWOPtwQbIS05PbEh3IJmkADRu5HAQ=="},
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"bs5sBXW61WZFajAPlwQtWPeqbgBtkCH6hfo6NslraPk="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":869426051,"port":30303}],"version":1596340014,"reinit_date":1596340014,"priority":0,"expire_at":0},"version":1596805014,"signature":"PGWWKYI1DNvwJlzoLYb6e4r4xAdxN769X6piHLu0/t4+k/rL2uO00IKvCNkfdyHzGWBmIZ7fWdfLnnsUiV4GDQ=="},
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"M7i0VqdFbeEFwFL0CIZM/fYE/l6qITojgwCjZC3wBIo="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":869429408,"port":30303}],"version":1596600825,"reinit_date":1596600825,"priority":0,"expire_at":0},"version":1596805008,"signature":"Ho0FBRiDrJMvURVzQfn8Tj1Rjx9REueJfuWdWCj9u9enwZlf0FxUvofaxPk0cnng9TjyxvP0ImhtRmTYjWfFBA=="},
                    {"@type":"dht.node","id":{"@type":"pub.ed25519","key":"zUlPnefrXYweFgX3En85GpBMcAnBd3glzhmGweqpigo="},"addr_list":{"@type":"adnl.addressList","addrs":[{"@type":"adnl.address.udp","ip":1760767044,"port":30310}],"version":1596587374,"reinit_date":1596587374,"priority":0,"expire_at":0},"version":1596805011,"signature":"2QQnriFK+TSEqjLo/RDIYrXIqUbJdTPeRkqLGX9OSNAQyv+uLq2OuCdN2ffeXAhmsmchQDoY8JRKe+4HxshuBA=="}
                ]
            }
        },
        "validator": {
            "@type": "validator.config.global",
            "zero_state": {
                "workchain": -1,
                "shard": -9223372036854775808,
                "seqno": 0,
                "root_hash": "hw7m9dVxoI9QzNp8jlOA9fxZeojPQS+T12KTEAXFzS8=",
                "file_hash": "OqQ7U32OCh0RI9EeRs9rCR78C6075Ff9WFk653M2qBk="
            }
        }
    }
